### ISSUE TITLE
Add support to pass in env variables to enable deployment of Kitura NIO apps

### ISSUE THREAD

**Issue by helenmasters** [IBM-Swift/swift-buildpack#113]
We need to add support to pass through environment variables to the swift-buildpack when performing `swift package resolve`, as currently we can't use Cloud Foundry to deploy a Kitura app to IBM Cloud which uses Kitura-NIO.

This is because to run on top of Kitura-NIO (instead of Kitura-Net) you need to set an environment variable called KITURA_NIO before building your Kitura application, e.g. `export KITURA_NIO=1 && swift build`

So we need to find a way to end up with `export KITURA_NIO && swift package resolve` set if the user has a Kitura application which they want to run with Kitura-NIO.

**Comment by christiancompton** [comment]
Closing as complete :)
