### ISSUE TITLE
For next release, ensure that following swift versions are cached (see description).

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/swift-buildpack#14]
Please note that some of these versions are already cached. Let's ensure that all versions listed below are included in the cached manifest:

swift-DEVELOPMENT-SNAPSHOT-2016-08-18-a
swift-DEVELOPMENT-SNAPSHOT-2016-08-07-a
swift-DEVELOPMENT-SNAPSHOT-2016-08-04-a
swift-DEVELOPMENT-SNAPSHOT-2016-07-25-a
swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a
swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a

**Comment by rolivieri** [comment]
@BDHernand I went ahead and updated the buildpack code accordingly to support the swift versions listed above. I will let you test it to verify that the changes actually work. I am in the middle of documenting the steps to follow for testing. I will let you know once I am done.

**Comment by rolivieri** [comment]
@BDHernand I have deployed the buildpack to staging with the above swift versions. Let's add now support for swift 08-26.

**Comment by BDHernand** [comment]
The following folder contains the docs I am putting together for the buildpack:

https://ibm.ent.box.com/files/0/f/11040341714/Buildpack___Bluemix


1) Let's start by making sure you have requested the necessary access; see the "Requesting System Access" note.

2) Add support to the Swift Buildpack on a separate branch (off develop) for swift 08-26 (https://github.com/IBM-Swift/swift-buildpack/issues/14).

3) Go over the "Creating The Buildpack ZIP Package"; make sure you can create a ZIP package on your Mac.

4) Go over "Testing the Buildpack Using BOSH-lite" and ensure you can set up your system to run BOSH-lite and install buildpacks for testing.

5) Go over "Swift Buildpack Testing on YS0" document and let's verify that you can deploy to YS0.

**Comment by BDHernand** [comment]
Ricardo,

   I'm in step 4 from the previous comment and its working fine, but when i try and do the following command:

cf create-buildpack swift_buildpack <full_path_to_buildpack> 1

It fails with a error code 413.  I looked on the web and it suggested changing the nginx.conf file to increase the client_file_size_max (think i spelt that correctly) to allow for bigger file uploads and that still failed.  Now when it says <full_path_to_buildpack> i'm putting in the full path to the file.
The update-buildpack gives me the same error.
