### ISSUE TITLE
Include a more recent Swift Runtime.

### ISSUE THREAD

**Issue by herzi** [IBM-Swift/swift-buildpack#2]
The latest version of swift supported by swift-buildpack is dev-2016-05-03a. This leaves me stuck at fixing my dependencies to e.g. Kitura 0.16.x and SwiftyJSON 7.0.x.

It would be easier to keep up with the development of these projects if I wouldn't be stuck on dev-2016-05-03a.

**Comment by yocaminobien** [comment]
As for me the swift runtime almost unusable when it builds on dev-2016-05-03 
Please update it to 2016-07-05 at least...

**Comment by rolivieri** [comment]
Quick update: We have installed today a newer version of the swift buildpack on Bluemix (three production regions) that support swift 3 development binaries from 06-06. We plan to update the buildpack soon one more time to support swift binaries from 06-20.

**Comment by rolivieri** [comment]
Quick fyi: The develop branch now has support for swift binaries from 06-20. Please note that this is not installed yet on bluemix. You can still reference the develop branch from the CF command line.

**Comment by rolivieri** [comment]
Quick fyi: The develop branch now supports downloading any Swift 3 **development** version that is available on Swift.org. Please note that this is not installed yet on Bluemix. You can still reference the **develop** branch from the CF command line when using the `cf push` command.
