### ISSUE TITLE
Setup CI using Travis CI.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/swift-buildpack#3]
- [x] Automate testing of the master branch using Kitura-Starter-Bluemix and Bluemix (dallas region)
- [x] Time pushing the master branch of Kitura-Starter (https://github.com/IBM-Bluemix/Kitura-Starter) and Bluemix (dallas region). It should be no longer than X and Y respectively (X and Y being parameters to the Travis CI job).
- [x] Fail the build if the timing check fails.
- [x] Automate ZIP package creation, renaming ZIP package to meet requirements by UCD, automate creation of Git tag & release, and upload ZIP to GitHub under new release.
- [x] Create simple bash shell script for uploading/FTPing buildpack to GSA (this script will not live in this repo, we will put it under the DevOps repo) -> this would take a few parameters: github tag, GSA credentials. Script will download corresponding buildpack ZIP and upload it to GSA under the corresponding folder. Let's place this script here: https://github.com/IBM-Swift/DevOps/swift@ibm/master/scripts_assets/shell_assets/
- [x] Parameterize the loop count for executing `cf push` to Bluemix.

References:
- https://docs.travis-ci.com/user/deployment/releases
- https://github.com/cloudfoundry/cf-release/issues/907 (bosh-lite - only local usage?)

Deferring for now (since it does seem feasible):
- [ ] Automate installation of ZIP on bosh-lite and execute tests. Once this is implemented, we will re-order the execution of these in the travis file. For instance, we should create the release after the buildpack has been fully tested.

**Comment by BDHernand** [comment]
@rolivieri do we have the X and Y values for Item 2?

**Comment by BDHernand** [comment]
also trying to see if we can capture the execution time for a step in travis...  not much documentation on this.

**Comment by rolivieri** [comment]
Use these for now:

- Kitura-Starter -> 3m
- Swift HelloWorld -> 1m 30s

**Comment by rolivieri** [comment]
@BDHernand And for measuring time, you can do this:

```
START_TIME=$SECONDS
dosomething
ELAPSED_TIME=$(($SECONDS - $START_TIME))
```

Reference: http://stackoverflow.com/questions/5152858/how-can-i-measure-a-duration-in-seconds-in-a-linux-shell-script

**Comment by BDHernand** [comment]
according to Travis CI issues:  https://github.com/travis-ci/travis-ci/issues/6060

they do not support vagrant.  I think were going to have to go with the softlayer approach.  What do you think?

**Comment by BDHernand** [comment]
We bumped up the timeouts for the following:

Kitura-Starter: 190
swift-helloworld: 130
