### ISSUE TITLE
Determine if we can use draft instead of pre-release.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/swift-buildpack#48]

**Comment by BDHernand** [comment]
email out to Travis support on this issue

**Comment by rolivieri** [comment]
@BDHernand - Moving this to the blocked lane until we hear from travis support. Also, given the new automation implemented yesterday to download the ZIP file from GitHub, we may need to use pre-release instead of draft (compare the URL for a pre-release and the URL for a draft).

**Comment by BDHernand** [comment]
Hey Brian,

Thanks for the update and I'm glad to hear you are making progress.

To have a better understanding of your situation, could you provide us the commands you are doing by hands that create your desired result? We will compare it with what's generated under the hood by Travis CI.

Thank again for your collaboration and we will continue from there.

Have a great weekend!

-- Dominic.

**Comment by BDHernand** [comment]
I tried manually to create a draft release.... Travis is behaving the same way that manually does.

create a tag
push the tag
from the GUI edit the tag and create a draft release from it.
once you save that on the GUI there are 2 entries in the releases tab.

**Comment by BDHernand** [comment]
So i'm thinking the answer is that we cant use draft

**Comment by rolivieri** [comment]
We are closing this since using a draft release will break our FTP script. The URL for a draft release cannot be computed/derived from the version.
