### ISSUE TITLE
Upload new ZIP file (buildpack_swift_v2.0.2-20161118-1326.zip) for v2.0.2 of the buildpack to YS0.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/swift-buildpack#56]

**Comment by BDHernand** [comment]
currently uploading a 2.1.2 to yso, but also kicked off a rebuild with deploy to true as well

**Comment by BDHernand** [comment]
2.0.2 buildpack is uploaded

**Comment by rolivieri** [comment]
@BDHernand 

- [ ] Let's test the buildpack in YS0 by pushing kitura-starter and swift-helloworld and ensure we have a successful push and re-push.
- [ ] Let's check today the status of the UCD pipeline again.
