### ISSUE TITLE
Deploy release v1.1.6 to Bluemix.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/swift-buildpack#8]

**Comment by spiridonkopicl** [comment]
Hi @rolivieri just wondering, if you know when it will be deployed ?  Thx.

**Comment by rolivieri** [comment]
Hello, I am afraid I am not sure. You can still reference the code in the develop branch in you'd like using this: `cf push -b https://github.com/IBM-Swift/swift-buildpack#develop`
