### ISSUE TITLE
Push to Bluemix fails

### ISSUE THREAD

**Issue by omaarr90** [IBM-Swift/swift-buildpack#9]
I created a Kitura App following the steps in Kitura. My app is running locally fine and even with Xcode. However, Pushing to Bluemix using this command 

```
cf push <AppName>
```

I get this error. 

```
-----> Installing Swift DEVELOPMENT-SNAPSHOT-2016-06-20-a
DEPENDENCY_MISSING_IN_MANIFEST: 'swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a.tar.gz'
Staging failed: Buildpack compilation step failed
```

The full output of the command is:
```
Using manifest file /Users/omaralshammari/Development/IBM_Bluemix/UsedBooks/manifest.yml

Creating app UsedBooks in org <Email Address> / space Dev as <Email Address>...
OK

Creating route usedbooks-penitent-volution.mybluemix.net...
OK

Binding usedbooks-penitent-volution.mybluemix.net to UsedBooks...
OK

Uploading UsedBooks...
Uploading app files from: /Users/omaralshammari/Development/IBM_Bluemix/UsedBooks
Uploading 3.2K, 12 files
Done uploading               
OK

Starting app UsedBooks in org <Email Address> / space Dev as <Email Address>...
-----> Downloaded app package (4.0K)
-----> Installing system level dependencies...
-----> Installing libblocksruntime0_0.1-1_amd64.deb
-----> Installing libblocksruntime-dev_0.1-1_amd64.deb
-----> Installing libcurl3_7.35.0-1ubuntu2.6_amd64.deb
-----> Installing libkqueue0_1.0.4-2ubuntu1_amd64.deb
-----> Installing libssl-dev_1.0.1f-1ubuntu2.19_amd64.deb
-----> Installing openssl_1.0.1f-1ubuntu2.19_amd64.deb
-----> Writing profile script...
-----> Buildpack version 1.1.4
-----> Installing Swift DEVELOPMENT-SNAPSHOT-2016-06-20-a
DEPENDENCY_MISSING_IN_MANIFEST: 'swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a.tar.gz'
Staging failed: Buildpack compilation step failed

FAILED
Error restarting application: BuildpackCompileFailed

```

manifest.yml file is:
```
applications:
- name: UsedBooks
  memory: 256M
  instances: 1
  random-route: true
  disk_quota: 1024M
```

Things to notice: I do not create CF App in Bluemix before pushing the app. Not sure if should I. However, After pushing the is created.

**Comment by rolivieri** [comment]
Hello, it looks like you are using code that is different from the master branch of BluePic. I would recommend you re-clone the master branch and use it as-is. The master branch of BluePic is compatible with the Swift 06-06 binaries. See the README for further details.

Looking at your error above, you are attempting to use swift 06-20 binaries, which is not supported.

**Comment by rolivieri** [comment]
Hello, the current version of the buildpack installed on Bluemix does not support swift 06-20 binaries. If you would like to push a swift app that uses the swift 06-20 binaries, then you can do this: cf push -b https://github.com/IBM-Swift/swift-buildpack#develop.

**Comment by omaarr90** [comment]
@rolivieri Yes that correct, I was using swift 06-20 binaries. and this command cf push -b https://github.com/IBM-Swift/swift-buildpack#develop solved the issue. Thank you.
