### ISSUE TITLE
Swift 4.1 support

### ISSUE THREAD

**Issue by KyeMaloy97** [IBM-Swift/swift-buildpack#98]
Swift 4.1 is nearing public release and the BuildPack will need to be updated to support 4.1 when it becomes available. Xcode 9.3 will ship with the 4.1 binaries, and is available today as a developer beta.

**Comment by christiancompton** [comment]
https://github.com/IBM-Swift/swift-buildpack/releases/tag/untagged-40c94aa648a2c19888c9
